---
title: "initial workflow"
output: html_document
date: "2026-03-08"
---
Required libraries
```{r}
library("tidyverse")
library("janitor")
library("naniar")
```



initial data reading and cleaning
```{r}
atlantic_argos <- read_csv("../input_files/AtlanticArgos.csv")

pacific_argos <- read_csv("../input_files/PacificArgos.csv")

pacific_tad <- read_csv("../input_files/Pacific_TAD.csv") %>% 
  clean_names()
```
required libraries
```{r}
library(akima)
library(viridis)
library(ggmap)
```
```{r}
register_stadiamaps("0ca4e2d5-36a9-4a89-ab81-cfc2f0ec1652", write = FALSE)

hull <- pacific_tad %>%
  slice(chull(lon, lat))

bbox <- c(
  left = min(pacific_tad$lon),
  bottom = min(pacific_tad$lat),
  right = max(pacific_tad$lon),
  top = max(pacific_tad$lat)
)

basemap <- get_stadiamap(
  bbox = bbox,
  zoom = 7,
  maptype = "alidade_smooth"
)

samplemap <- ggmap(basemap) +
  geom_polygon(
    data = hull,
    aes(lon, lat),
    fill = "white",
    color = "black",
    alpha = 0.3
  ) +
  labs(
    title = "Sampled Region of Pacific Mako Sharks",
    x = "Longitude",
    y = "Latitude"
  )+
  theme(plot.title = element_text(hjust = 0.5))

samplemap

ggsave("../output_files/samplemap.png", plot = samplemap, width = 7, height = 5, units = "in", dpi = 600)
```


```{r}
library(maps)

world <- map_data("world")
```


```{r}
deepdata <- pacific_tad %>%
  mutate(
    deep_time = b100 + b150 + b200 + b_200
  )

interp_data <- with(deepdata, interp(x = lon, y = lat, z = deep_time, duplicate = "mean"))

interp_df <- expand.grid(
  lon = interp_data$x,
  lat = interp_data$y
)

interp_df$deep_time <- as.vector(interp_data$z)

divingheatmap <- ggplot()+
  geom_raster(data = interp_df,
              aes(
                x = lon, 
                y = lat, 
                fill = deep_time)
              )+
  geom_polygon(data = world,
               aes(x = long, y = lat, group = group),
               fill = "white",
               color = "black",
               linewidth = 0.2)+
  scale_fill_viridis_c(
    name = "Proportion Time > 100 m",
    limits = c(0,1),
    option = "cividis",
    na.value = NA
  )+
  coord_fixed(
  xlim = range(interp_df$lon) + c(-2,2),
  ylim = range(interp_df$lat) + c(-2,2)
  )+
  theme_classic() +
  labs(
    title = "Heatmap of Deep Diving Behavior",
    x = "Longitude",
    y = "Latitude"
  )

divingheatmap
  
```
```{r}
sst_interp <- with(pacific_tad,
  interp(x = lon, y = lat, z = sst, duplicate = "mean")
)

sst_df <- expand.grid(
  lon = sst_interp$x,
  lat = sst_interp$y
)

sst_df$SST <- as.vector(sst_interp$z)

tempheatmap <- ggplot()+
  geom_raster(data = sst_df,
              aes(
                x = lon, 
                y = lat, 
                fill = SST)
              )+
  geom_polygon(data = world,
               aes(x = long, y = lat, group = group),
               fill = "white",
               color = "black",
               linewidth = 0.2)+
  scale_fill_viridis_c(name = "Sea Surface Temp (°C)",
                       option = "magma",
                       na.value = NA
                       )+
  coord_fixed(
    xlim = range(interp_df$lon) + c(-2,2),
    ylim = range(interp_df$lat) + c(-2,2)
  )+
  theme_classic()+
  labs(
    title = "Heatmap of Ocean Surface Temperature",
    x = "Longitude",
    y = "Latitude"
  )

tempheatmap
```
```{r}
do_interp <- with(pacific_tad,
  interp(x = lon, y = lat, z = do_depth, duplicate = "mean")
)

do_df <- expand.grid(
  lon = do_interp$x,
  lat = do_interp$y
)

do_df$DO_depth <- as.vector(do_interp$z)

doheatmap <- ggplot()+
  geom_raster(data = do_df,
              aes(
                x = lon, 
                y = lat, 
                fill = DO_depth)
              )+
  geom_polygon(data = world,
               aes(x = long, y = lat, group = group),
               fill = "white",
               color = "black",
               linewidth = 0.2)+
  scale_fill_viridis_c(name = "Hypoxic Boundary Depth (m)",
                       na.value = NA
                       )+
  coord_fixed(
    xlim = range(interp_df$lon) + c(-2,2),
    ylim = range(interp_df$lat) + c(-2,2)
  )+
  theme_classic()+
  labs(
    title = "Heatmap of Hypoxic Boundary Depth",
    x = "Longitude",
    y = "Latitude"
  )

doheatmap
```
```{r}
ggsave("../output_files/divingheatmap.png", plot = divingheatmap, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/tempheatmap.png", plot = tempheatmap, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/doheatmap.png", plot = doheatmap, width = 7, height = 5, units = "in", dpi = 600)
```

trend graphs of dive depth to do depth
```{r}
b_50plot <- pacific_tad %>% 
  select(id, do_depth, b_50) %>% 
  ggplot(
    mapping = aes(
      x = do_depth,
      y = b_50,
      )
    )+
    geom_point(
      alpha = 0.5,
      color = "tan"
      )+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Oxygen Boundry vs Proportion of Time, Above 50 m",
      x = "Dissolved Oxygen Boundry (m)",
      y = "Proportion of Time"
    )
```
```{r}
b100plot <- pacific_tad %>% 
  select(id, do_depth, b100) %>% 
  ggplot(
    mapping = aes(
      x = do_depth,
      y = b100,
      )
    )+
    geom_point(
      alpha = 0.5,
      color = "tan"
      )+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Oxygen Boundry vs Proportion of Time, 50 - 100 m",
      x = "Dissolved Oxygen Boundry (m)",
      y = "Proportion of Time"
    )
```
```{r}
b150plot <- pacific_tad %>% 
  select(id, do_depth, b150) %>% 
  ggplot(
    mapping = aes(
      x = do_depth,
      y = b150,
      )
    )+
    geom_point(
      alpha = 0.5,
      color = "tan"
      )+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Oxygen Boundry vs Proportion of Time, 100 - 150 m",
      x = "Dissolved Oxygen Boundry (m)",
      y = "Proportion of Time"
    )
```
```{r}
b200plot <- pacific_tad %>% 
  select(id, do_depth, b200) %>% 
  ggplot(
    mapping = aes(
      x = do_depth,
      y = b200,
      )
    )+
    geom_point(
      alpha = 0.5,
      color = "tan"
      )+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Oxygen Boundry vs Proportion of Time, 150 - 200 m",
      x = "Dissolved Oxygen Boundry (m)",
      y = "Proportion of Time"
    )
```
```{r}
b_200plot <- pacific_tad %>% 
  select(id, do_depth, b_200) %>% 
  ggplot(
    mapping = aes(
      x = do_depth,
      y = b_200,
      )
    )+
    geom_point(
      alpha = 0.5,
      color = "tan"
      )+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Oxygen Boundry vs Proportion of Time, Below 200 m",
      x = "Dissolved Oxygen Boundry (m)",
      y = "Proportion of Time"
    )
```

```{r}
ggsave("../output_files/b_50plot.png", plot = b_50plot, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b100plot.png", plot = b100plot, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b150plot.png", plot = b150plot, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b200plot.png", plot = b200plot, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b_200plot.png", plot = b_200plot, width = 7, height = 5, units = "in", dpi = 600)

```

trends of surface temperature to dive depth
```{r}
b_50plottemp <- pacific_tad %>% 
  select(id, sst, b_50) %>% 
  ggplot(
    mapping = aes(
      x = sst,
      y = b_50)
    )+
    geom_point(
      alpha = 0.5,
      color = "pink")+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Ocean Surface Temperature  vs Proportion of Time, Above 50 m",
      x = "Ocean Surface Temperature (°C)",
      y = "Proportion of Time"
    )
```
```{r}
b100plottemp <- pacific_tad %>% 
  select(id, sst, b100) %>% 
  ggplot(
    mapping = aes(
      x = sst,
      y = b100)
    )+
    geom_point(
      alpha = 0.5,
      color = "pink")+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Ocean Surface Temperature  vs Proportion of Time, 50 - 100 m",
      x = "Ocean Surface Temperature (°C)",
      y = "Proportion of Time"
    )
```
```{r}
b150plottemp <- pacific_tad %>% 
  select(id, sst, b150) %>% 
  ggplot(
    mapping = aes(
      x = sst,
      y = b150)
    )+
    geom_point(
      alpha = 0.5,
      color = "pink")+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Ocean Surface Temperature  vs Proportion of Time, 100 - 150 m",
      x = "Ocean Surface Temperature (°C)",
      y = "Proportion of Time"
    )
```
```{r}
b200plottemp <- pacific_tad %>% 
  select(id, sst, b200) %>% 
  ggplot(
    mapping = aes(
      x = sst,
      y = b200)
    )+
    geom_point(
      alpha = 0.5,
      color = "pink")+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Ocean Surface Temperature  vs Proportion of Time, 150 - 200 m",
      x = "Ocean Surface Temperature (°C)",
      y = "Proportion of Time"
    )
```
```{r}
b_200plottemp <- pacific_tad %>% 
  select(id, sst, b_200) %>% 
  ggplot(
    mapping = aes(
      x = sst,
      y = b_200)
    )+
    geom_point(
      alpha = 0.5,
      color = "pink")+
    geom_smooth(
      se = FALSE,
      method = lm,
      color = "black"
    )+
    theme_classic()+
    labs(
      title = "Ocean Surface Temperature  vs Proportion of Time, Below 200 m",
      x = "Ocean Surface Temperature (°C)",
      y = "Proportion of Time"
    )
```

```{r}
ggsave("../output_files/b_50plottemp.png", plot = b_50plottemp, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b100plottemp.png", plot = b100plottemp, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b150plottemp.png", plot = b150plottemp, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b200plottemp.png", plot = b200plottemp, width = 7, height = 5, units = "in", dpi = 600)
ggsave("../output_files/b_200plottemp.png", plot = b_200plottemp, width = 7, height = 5, units = "in", dpi = 600)

```


niche of sharks
```{r}
dengraph <- ggplot(pacific_tad, aes(x = sst, y = do_depth)) +
  stat_density_2d(
    aes(fill = after_stat(level)),
    geom = "polygon",
    alpha = 0.7
  ) +
  scale_fill_viridis_c(name = "Use Density",
                      option = "cividis") +
  theme_classic() +
  labs(
    title = "Temperature–Oxygen Habitat Envelope",
    x = "Temperature (°C)",
    y = "Dissolved Oxygen"
  )

ggsave("../output_files/dengraph.png", plot = dengraph, width = 7, height = 5, units = "in", dpi = 600)
```

```{r}
depth_long <- pacific_tad %>% 
  mutate(
      depth_zone = case_when(
        do_depth < 100 ~ "Above 100 m",
        do_depth >= 100 & do_depth <= 200 ~ "100-200 m",
        do_depth > 200 ~ "Below 200 m"
      )
  ) %>%
  pivot_longer(
    cols = c(b_50, b100, b150, b200, b_200),
    names_to = "depth_bin",
    values_to = "time_prop"
  )

depth_long$depth_bin <- factor(
  depth_long$depth_bin,
  levels = c("b_50","b100","b150","b200","b_200")
)

depth_long$depth_zone <- factor(
  depth_long$depth_zone,
  levels = c("Above 100 m", "100-200 m", "Below 200 m")
)

disgraph <- ggplot(depth_long, aes(x = depth_bin, y = time_prop)) +
  geom_boxplot(fill = "tan", alpha = 0.7) +
  theme_minimal()+
  coord_flip()+
  labs(
    title = "Distribution of Time at Each Depth by Dissolved Oxygen Boundry Depth",
    x = "Depth Range",
    y = "Proportion of Time"
  )+
  facet_wrap(~depth_zone)+
  theme(plot.title = element_text(hjust = 0.5))+
  theme_classic()

disgraph

ggsave("../output_files/disgraph.png", plot = disgraph, width = 7, height = 5, units = "in", dpi = 600)
```
```{r}
relategraph <- pacific_tad %>%
  ggplot(aes(x = sst, y = do_depth)) +
  geom_point(alpha = 0.6, color = "#028284") +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  theme_classic() +
  labs(
    x = "Sea Surface Temperature (°C)",
    y = "Dissolved Oxygen Depth",
    title = "Relationship Between SST and DO Depth"
  )

relategraph

ggsave("../output_files/relategraph.png", plot = relategraph, width = 7, height = 5, units = "in", dpi = 600)

```





