---
title: "shiny"
output: html_document
date: "2026-03-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(shiny)
library(leaflet)
library(dplyr)

ui <- fluidPage(

  titlePanel("Pacific Mako Shark Habitat Explorer"),

  sidebarLayout(

    sidebarPanel(

      selectInput(
        "shark_id",
        "Select Shark ID",
        choices = unique(pacific_tad$id)
      ),

      checkboxInput(
        "show_points",
        "Show Points",
        TRUE
      )

    ),

    mainPanel(
      leafletOutput("shark_map", height = 700)
    )

  )
)

server <- function(input, output) {

  filtered_data <- reactive({

    pacific_tad %>%
      filter(id == input$shark_id)

  })

  output$shark_map <- renderLeaflet({

    leaflet() %>%
      addProviderTiles("CartoDB.Positron") %>%
      setView(lng = -135, lat = 30, zoom = 4)

  })

  observe({

    data <- filtered_data()

    if(nrow(data) == 0) return()

    leafletProxy("shark_map") %>%

      clearMarkers() %>%
      clearShapes() %>%

      addPolylines(
        data = data,
        lng = ~lon,
        lat = ~lat,
        color = "black",
        weight = 3
      ) %>%

      addCircleMarkers(
        data = data,
        lng = ~lon,
        lat = ~lat,
        radius = 4,
        color = "tan",
        popup = ~paste0(
          "<br><b>Date:</b> ", date,
          "<br><b>Depth:</b> ", round(do_depth,1), " m",
          "<br><b>SST:</b> ", round(sst,2)
        ),
        opacity = ifelse(input$show_points, 1, 0)
      )

  })

}

shinyApp(ui, server)
```

